# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "fedora/27-cloud-base"
  #config.vm.box = "generic/ubuntu1710"
  config.ssh.forward_agent = true

  config.vm.provider :libvirt do |libvirt|
    libvirt.cpu_mode = "host-passthrough"
    libvirt.nested = true
    libvirt.memory = "8192"
    libvirt.machine_virtual_size = 80
  end

  config.vm.provision "ansible" do |ansible|
    ansible.verbose = "v"
    ansible.playbook = "playbook.yml"
    ansible.extra_vars = { ansible_python_interpreter:"/usr/bin/python3" }
  end

  config.vm.provision "ansible" do |ansible_dev|
    ansible_dev.verbose = "v"
    ansible_dev.playbook = "dev.yml"
    ansible_dev.extra_vars = { ansible_python_interpreter:"/usr/bin/python3" }
  end

end
