# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  #config.vm.box = "fedora/27-cloud-base"
  config.vm.box = "generic/ubuntu1604"
  config.ssh.forward_agent = true

  for playbook in ["ubuntu", "dev", "gui"]
    config.vm.provision "ansible" do |ansible|
      ansible.verbose = "v"
      ansible.playbook = "../_ansible/#{playbook}.yml"
      ansible.extra_vars = { ansible_python_interpreter:"/usr/bin/python3" }
    end
  end

end
