# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "fedora/27-cloud-base"
  #config.vm.box = "generic/ubuntu1710"
  config.ssh.forward_agent = true

  config.vm.provider :libvirt do |libvirt|
    libvirt.cpu_mode = "host-passthrough"
    libvirt.nested = true
    libvirt.memory = "4096"
  end

  for playbook in ["dev", "nested", "libvirt", "kubectl", "minikube"]
    config.vm.provision "ansible" do |ansible|
      ansible.verbose = "v"
      ansible.playbook = "../_ansible/#{playbook}.yml"
      ansible.extra_vars = { ansible_python_interpreter:"/usr/bin/python3" }
    end
  end

end
