---
- hosts: all
  tasks:
    - name: install git
      package:
        name: git
        state: present
      become: true

    - name: clone repos
      git:
        repo: git@github.com:booxter/{{item}}.git
        dest: "{{item}}"
      with_items:
        - ct
        - ibrest
      ignore_errors: true

    - name: install native dependencies
      package:
        name: python3-tkinter,gnuplot,bc
        state: present
      become: true

    - name: prepare ct venv
      command: tox -e py36 --notest
      args:
        chdir: ct
        creates: .tox/py36/bin/python
