---
- hosts: all
  tasks:
    - name: upgrade all packages
      package: name=* state=latest
      become: true

    - name: install dev tools
      package:
        name: git,tig,vim-enhanced,tmux,gcc,ctags,vagrant,libvirt-client,ansible,buildah
        state: present
      become: true

    - name: install dev tools (redhat)
      package:
        name: redhat-rpm-config
        state: present
      become: true
      when:
        - ansible_os_family == "RedHat"

    - name: install debug tools
      package:
        name: psmisc
        state: present
      become: true

    - name: install networking tools
      package:
        name: bridge-utils,lsof,tcpdump,telnet
        state: present
      become: true

    - name: register github fingerprint
      lineinfile:
        dest: .ssh/known_hosts
        line: "{{ lookup('file', '../_files/ssh_keys/github.com') }}"
        create: yes

    - name: install Vundle
      git:
        repo: https://github.com/VundleVim/Vundle.vim.git
        dest: .vim/bundle/Vundle.vim

    - name: copy vimrc
      copy:
        src: ../_files/vimrc
        dest: /home/{{ ansible_user }}/.vimrc

    - name: install vundle plugins
      command: vim +PluginInstall +qall

    - name: set default git email
      command: git config --global user.email "ihar.hrachyshka@gmail.com"

    - name: set default git name
      command: git config --global user.name "Ihar Hrachyshka"
