---
- hosts: all
  become: true
  vars:
    exec_docker: |
      #!/bin/sh
      sudo /usr/bin/docker $*
    exec_docker_compose: |
      #!/bin/sh
      sudo /usr/bin/docker-compose $*
  tasks:
    - name: install docker
      package:
        name: docker,docker-compose
        state: present

    - name: start docker
      systemd:
        name: docker
        enabled: yes
        state: started

    - name: configure password-less docker
      lineinfile:
        path: /etc/sudoers
        state: present
        line: '%wheel ALL=(ALL) NOPASSWD: /usr/bin/docker'

    - name: configure password-less docker-compose
      lineinfile:
        path: /etc/sudoers
        state: present
        line: '%wheel ALL=(ALL) NOPASSWD: /usr/bin/docker-compose'

    - name: always execute docker via sudo
      copy:
        content: '{{ exec_docker }}'
        dest: /usr/local/bin/docker
        mode: 0755

    - name: always execute docker-compose via sudo
      copy:
        content: '{{ exec_docker_compose }}'
        dest: /usr/local/bin/docker-compose
        mode: 0755

    - name: adding {{ ansible_user }} to wheel group
      user:
        name={{ ansible_user }}
        groups=wheel
        append=yes
      become: true
