---
- hosts: all
  become: true
  tasks:
    - name: install libvirt environment
      package:
        name: libvirt,libvirt-daemon-kvm,libvirt-client,qemu-kvm
        state: present

    - name: adding {{ ansible_user }} to libvirt group
      user:
        name={{ ansible_user }}
        groups=libvirt
        append=yes

    - name: start libvirtd
      systemd:
        name: libvirtd
        enabled: yes
        state: started

    - name: autostart default network
      command: virsh net-autostart default
